version: "3.8"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=atmi
      - POSTGRES_PASSWORD=atmi
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentalx
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: .
        target: /usr/app

volumes:
  pgdata:
